echo ""
echo "rm -rf build"
rm -rf build

echo ""
echo "mkdir build"
mkdir build

echo ""
echo "javac -d build java/com/hds/aw/commons/librsync/*.java"
javac -d build java/com/hds/aw/commons/librsync/*.java

echo ""
echo "javah -classpath build -d build com.hds.aw.commons.librsync.LibrsyncWrapper"
javah -classpath build -d build com.hds.aw.commons.librsync.LibrsyncWrapper

echo ""
echo "cp c/*.* build/."
cp c/*.* build/.

echo ""
echo "cp lib/librsync.so.1 build/."
cp lib/librsync.so.1 build/.

echo ""
echo "cd build"
cd build

echo ""
echo "ln -s librsync.so.1 librsync.so"
ln -s librsync.so.1 librsync.so

echo ""
echo "gcc -fPIC -c LibrsyncWrapper.c -I $JAVA_HOME/include -I $JAVA_HOME/include/linux -I ."
gcc -fPIC -c LibrsyncWrapper.c -I $JAVA_HOME/include -I $JAVA_HOME/include/linux -I .

echo ""
echo "gcc LibrsyncWrapper.o -shared -o librsyncWrapper.so -Wl,-rpath,. -L. -lrsync"
gcc LibrsyncWrapper.o -shared -o librsyncWrapper.so -Wl,-rpath,. -L. -lrsync

echo ""
echo "export LD_LIBRARY_PATH=."
export LD_LIBRARY_PATH=.

echo ""
echo "java -Djava.library.path=. com.hds.aw.commons.librsync.LibrsyncWrapperTest ../data/file.base ../data/file.changed file.sig file.delta file.patch"
java -Djava.library.path=. com.hds.aw.commons.librsync.LibrsyncWrapperTest ../data/file.base ../data/file.changed file.sig file.delta file.patch

echo ""
echo "file.base, the original file:"
ls -l ../data/file.base

echo ""
echo "file.changed, the modified file:"
ls -l ../data/file.changed

echo ""
echo "delta file generated by librsync:"
ls -l file.delta

echo ""
echo "patched file, which should be exactly the same as file.changed:"
ls -l file.patch

