package com.hds.aw.commons.librsync;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.ByteBuffer;

/**
 * Consumes output produced by librsync. For example, for a librsync signature job, the output to
 * consume is the actual signature generated by librsync.
 * 
 * This implementation writes the output to a provided OutputStream
 *
 * @author Beth Tirado, Hitachi Data Systems
 */
public class OutputStreamConsumer implements RsyncOutputConsumer {
    private OutputStream[] outStreams;
    private byte[] bytes;

    /**
     * Construct an OutputStreamConsumer that will consume the librsync output
     * 
     * @param outputStreams
     *            output is consumed and written to all provided OutputStreams
     */
    public OutputStreamConsumer(OutputStream... outputStreams) {
        outStreams = outputStreams;
    }

    /**
     * Consumes output previously written to buf and writes it to the OutputStream provided in the
     * Constructor
     * 
     * @param buf
     *            the buffer containing output to consume
     */
    public void consumeOutput(ByteBuffer buf) throws IOException {
        if (bytes == null || bytes.length < buf.remaining()) {
            bytes = new byte[buf.capacity()];
        }

        int cnt = buf.remaining();
        buf.get(bytes, 0, cnt);
        for (OutputStream out : outStreams) {
            out.write(bytes, 0, cnt);
        }
    }
}
